### ISSUE TITLE
Inline Codes

### ISSUE THREAD

**Issue by Hashemian01** [mwxgaf/obsidian-dynamic-rtl#10]
Inline codes (`Inline codes`) are empty in reading view when Dynamic RTL Plugin is active
![image](https://user-images.githubusercontent.com/48093461/198879216-ac247314-f1db-4db1-8b40-0fdad5ed7323.png)

**Comment by mwxgaf** [comment]
Fixed !
Thank you so so much :rose:
Please wait for the new version to release.
