### ISSUE TITLE
Bullet Points Order in Reading View

### ISSUE THREAD

**Issue by Hashemian01** [mwxgaf/obsidian-dynamic-rtl#13]
When we have LTR First and RTL second, there is a bug in bullet points in reading view

![image](https://user-images.githubusercontent.com/48093461/199511505-aef57ce4-f181-4d62-8e23-76851d026f84.png)

**Comment by mwxgaf** [comment]
Fixed !
Thank you so much :rose:
Wait for the new version to release.
