### ISSUE TITLE
Hyperlinks

### ISSUE THREAD

**Issue by Hashemian01** [mwxgaf/obsidian-dynamic-rtl#15]
This is minor problem, but I decided to post it anyways. In reading view, the hyperlink arrow should be on the left side of RTL links
![image](https://user-images.githubusercontent.com/48093461/199536565-cb138d17-f2d1-4902-a372-9efe799ea7b2.png)

**Comment by mwxgaf** [comment]
@Hashemian01 
Fixed!
Wait for the new version to release.
I appreciate your exact, detailed & helpful issues and I know you have taken a lot of trouble to produce these pictures & details & this is so valuable. Thank you so much :rose: :heart: 
I will mention you in release notes & that is all I can do to thank you.

**Comment by mwxgaf** [comment]
[New version](https://github.com/mwxgaf/obsidian-dynamic-rtl/releases/tag/0.2.9) released!
