### ISSUE TITLE
Custom font for RTL lines

### ISSUE THREAD

**Issue by Lulullia** [mwxgaf/obsidian-dynamic-rtl#16]
Assalamou alaykoum

First of all, thanks a lot for this, now I can study Islam inside Obsidian! BarakaLlahou fik

It would be nice if we could set a custom font for RTL lines. Like "Arabic Typesetting" font but it could be a setting.
Eventually we could also adjust font size.

If it's not possible to make a setting, at least give a CSS class to RTL lines so we can style them?

Thank you.

**Comment by mwxgaf** [comment]
Alaykom Assalam 💚 
I am so happy to hear this:
> now I can study Islam inside Obsidian

But about fonts: It comes to my mind that it **may** be possible in reading view but it is not what every one desires which requires settings part for the plugin that **may** I do this in future in-sha-Allah.
You can set the editor font family & font size from the settings 👉 appearance part.
You can mix you desired Arabic font with an English font to have what do you want.  For example the Arabic/Persian Vazirmatn font uses Roboto for English characters.
I will close this as complete but you can continue the discussion by comment or reopen this every time you would like & I will check & answer as soon as I can.
Pray for me 🌹

**Comment by mwxgaf** [comment]
Why it overrides your font? Do you mean the mobile version?
Lines direction is dynamic in most of cases. Almost generally there is no RTL lines to target for styling.
