### ISSUE TITLE
Incorrect line position for bullet list

### ISSUE THREAD

**Issue by ShahriarKh** [mwxgaf/obsidian-dynamic-rtl#17]
The line should be on the right side of the list, not between the bullet and text.
![image](https://user-images.githubusercontent.com/31452340/201520850-950ea84a-ebe6-4509-90ca-5d92bd319d8c.png)

**Comment by mwxgaf** [comment]
Hi
Thank you for the issue.
Is this in reading view or live preview/editing mode?

**Comment by ShahriarKh** [comment]
Hi
In Reading view

**Comment by mwxgaf** [comment]
Fixed!
Wait for new version to release & check if your problem is fixed or not.
Thanks for your issue :rose:
