### ISSUE TITLE
Dynamically change font for RTL content

### ISSUE THREAD

**Issue by ma-sadeghi** [mwxgaf/obsidian-dynamic-rtl#19]
I'm not very familiar with web technologies, so forgive me if this sounds absurd! 

Is there a way to dynamically change the font for RTL content?

**Comment by mwxgaf** [comment]
Hi
Yes there is. The raw first idea that comes to my mind is using `getComputedStyle` but it probably causes performance problems.
Mixing your favorite English & Persian font may be helpful (i.e VazirMatn misc version + OpenSans | By default , VazirMatn is mixed with Roboto)
Persian user manual for this action could be found in VazirMatn website

**Comment by ma-sadeghi** [comment]
Great, thank you for the detailed response!
