### ISSUE TITLE
Plugin not available on Obsidian

### ISSUE THREAD

**Issue by ma-sadeghi** [mwxgaf/obsidian-dynamic-rtl#2]
I wasn't able to find your plugin in Obsidian, is it officially released yet? Thanks!

**Comment by mwxgaf** [comment]
> I wasn't able to find your plugin in Obsidian, is it officially released yet? Thanks!

Hi! 
I submitted the plugin & it is still waiting to be reviewed by Obsidian team. It will take a few days.

**Comment by ma-sadeghi** [comment]
Thank you so much for creating this amazing plugin Amirreza!

**Comment by aliamini87** [comment]
I suggest add this answer to the readme file.

**Comment by aliamini87** [comment]
Hi
There isn't script.js in the files! Do you mean main.js that is in the releases page?

**Comment by mwxgaf** [comment]
> I suggest add this answer to the readme file.

Thanks I will do this soon
