### ISSUE TITLE
Suggestioin for RTL direction while text align is left

### ISSUE THREAD

**Issue by amirtq** [mwxgaf/obsidian-dynamic-rtl#21]
Hi there
Current version supports the RTL for texts those are starting with a RTL word and put them at the right of the note.
Sometimes, you may need the text align to be on the left but the direction to be RTL
It is very good if you add an option to the right click menu to change the direction for an individual line no matter of it's default behavior.

Regards

**Comment by amrsamii** [comment]
I really appreciate this kind of enhancement!

**Comment by mwxgaf** [comment]
Hi
Thank you for your issue. But unfortunately there is not any specified <<RTL Line>> or even <<Line>> to target for styling.
All styles are global.

**Comment by amrsamii** [comment]
At least I want be able to enable/disable the plugin for certain files.

**Comment by amrsamii** [comment]
> > At least I want be able to enable/disable the plugin for certain files.
> 
> Obsidian RTL plugin supports this

But it's not dynamic as yours. I want to enable the plugin for certain files to be dynamic and not for all files.

**Comment by mwxgaf** [comment]
> > > At least I want be able to enable/disable the plugin for certain files.
> > 
> > 
> > Obsidian RTL plugin supports this
> 
> But it's not dynamic as yours. I want to enable the plugin for certain files to be dynamic and not for all files.

I'm sad to say this but I am so busy & this is not some thing that could be done by a few lines of code. Sorry for now :cry:
