### ISSUE TITLE
Obsidian 1.0.0

### ISSUE THREAD

**Issue by Hashemian01** [mwxgaf/obsidian-dynamic-rtl#3]
Hi. Some blocks including bullet lists and callouts stopped working in the latest Obsidian 1.0.0 . 

Also it would be nice if you could change the direction for the quotes frame.

![eview](https://user-images.githubusercontent.com/48093461/195636217-a8346a63-37af-4032-b035-06bcc08f19f7.png)
![rview](https://user-images.githubusercontent.com/48093461/195636248-e33f1fee-02b2-412b-b4d0-0791881d8f02.png)

**Comment by mwxgaf** [comment]
Thank you for submitting this issue
I am working on it.
I fixed the note title & callouts title (Not commited yet) & I am working on other problems

**Comment by mwxgaf** [comment]
New version released that fixes your issues :point_right: [Version 0.2.0](https://github.com/mwxgaf/obsidian-dynamic-rtl/releases/tag/0.2.0)
Please check if does it solves your problems or not & tell if you faced any other problems.
Thank you very much :heart: :rose:

**Comment by Hashemian01** [comment]
Wow. That was fast 😄
Now everything works fine again. Thanks
