### ISSUE TITLE
Support for other RTL languages.

### ISSUE THREAD

**Issue by nezirhaj** [mwxgaf/obsidian-dynamic-rtl#6]
Hello,

Firstly, BIG THANK for the plugin.
I tried to use this plugin for RTL languages which isn't Arabic or Persian, unfortunately it is look like the plugin support only arabic/presian alphabet. So, i tried to change the code, but there is an error when i do *npm run build* (It happens also in the non-touched code - with the persian alphabet) . (it doesn't happens with other plugins) (I don't have much experience with coding - so maybe it is mistake on my behalf). Thank in adavance.

![a123](https://user-images.githubusercontent.com/116385222/197270287-afaad438-e7d9-432a-ae1c-04ef8e683beb.JPG)

**Comment by mwxgaf** [comment]
Hi
Plugin supports all right to left languages except in some options & they will be fixed if you give me a COMPLETELY FULL list of your languages alphabet (+ All other characters (numbers,...)).

& about errors:
Yes this is my bad, because unfortunately some times I don't fill like to care about TypeScript laws.
run `npm run dev` then `main.js` will be usable (s.th like build)

**Comment by nezirhaj** [comment]
> Hi Plugin supports all right to left languages except in some options & they will be fixed if you give me a COMPLETELY FULL list of your languages alphabet (+ All other characters (numbers,...)).
> 
> & about errors: Yes this is my bad, because unfortunately some times I don't fill like to care about TypeScript laws. run `npm run dev` then `main.js` will be usable (s.th like build)

**Comment by nezirhaj** [comment]
Thanks, (I think maybe i

**Comment by nezirhaj** [comment]
Hi,
If it possible I would like to add Hebrew support for the plugin.
Here is the alphabet:
const chars = ['ק','ר','א','ט','ו','ן','ם','פ','ש','ד','ג','כ','ע',`י`,`ח`,`ל`,`ך`,`ף`,`ז`,`ס`,`ב`,`ה`,`נ`,`מ`,`צ`,`ת`,`ץ`]; 

Hebrew doesn't have special symbols for numbers.

Thanks! :)

(BTW, I think i closed the comment section by mistake)

**Comment by mwxgaf** [comment]
Errors problem is fixed in [new release](https://github.com/mwxgaf/obsidian-dynamic-rtl/releases/tag/0.2.3).
Thank you so so much for the alphabet I will add it right now

**Comment by mwxgaf** [comment]
@nezirhaj
Fixed :point_right: [`0.2.4`](https://github.com/mwxgaf/obsidian-dynamic-rtl/releases/tag/0.2.4)
I mentioned you in release notes.
:heart: Thank you so much

**Comment by nezirhaj** [comment]
Thanks! 😀
