### ISSUE TITLE
No margin between the bullet and the text in RTL lists

### ISSUE THREAD

**Issue by ma-sadeghi** [mwxgaf/obsidian-dynamic-rtl#8]
![image](https://user-images.githubusercontent.com/14086031/198373499-1c14f13f-ec90-4183-b201-52f6deeaba9e.png)

**Comment by mwxgaf** [comment]
This was fixed in previous versions.
are you using the last version?

**Comment by ma-sadeghi** [comment]
I just figured out that it was because I was using the "Minimal" theme. Using the default theme, it works. I'll open up an issue over there. Thanks!

**Comment by mwxgaf** [comment]
I changed my theme to minimal today & fixed the problem. new release will be published soon please do not open another issue for the same problem.
I fixed that
Just wait for the new version
:heart:  Thanks for the issue

**Comment by mwxgaf** [comment]
Fixed in v0.2.7
Please update the plugin from app.
Thank you so much :rose:

**Comment by nezirhaj** [comment]
HI, I have problem with bullet points with the ITS theme. If it's ok to ask, maybe you could Fix the problem.

editing view:
![Capture](https://user-images.githubusercontent.com/116385222/200031712-855b1279-a1fb-4dc7-aa21-1b979ca74e33.PNG)

reading view:
![Capture1](https://user-images.githubusercontent.com/116385222/200031965-1a09a994-2960-461e-8d14-d28865c19e3f.PNG)
