### ISSUE TITLE
Incompatiblity with Tasks plugin

### ISSUE THREAD

**Issue by ma-sadeghi** [mwxgaf/obsidian-dynamic-rtl#9]
# `dynamic-rtl` enabled

![image](https://user-images.githubusercontent.com/14086031/198566842-b6d3ca47-f2e3-45f5-8f6b-511ee1e283b1.png)

# `dynamic-rtl` disabled

![image](https://user-images.githubusercontent.com/14086031/198567070-ca14710e-33d7-4228-bbb6-a00b8fa9218e.png)

**Comment by mwxgaf** [comment]
Solved in `0.2.8`.
Please update the plugin from app.
Thank you for the issue :rose:

**Comment by ma-sadeghi** [comment]
Amazing! Your plugin is my favorite. RTL compatibility is important enough for it to even be part of the Obsidian app as a core plugin. Anyway, thanks for all your efforts!

**Comment by mwxgaf** [comment]
Thanks!
RTL Should be fixed from main source code of the app. What I do in the plugin almost is ماله کشی 😉

**Comment by aliamini87** [comment]
Obsidian also ahs RTL support but it is document-based not paragraph-based.
They talk about code-mirror as a cause for disability to go beyond document-based RTL. Are they right?

**Comment by mwxgaf** [comment]
I know.
No they are not right completely.
I solved many problems just with a plugin while it does not have access to many things, how it will be if I access the main source code?
The user who was in charge to approve the plugin to be published, didn't believe that plugin works in live preview mode too until I recorded & uploaded a video for him/her !!! At that time I thought that they were disappointed from bidi documents; but it is completely possible, just needs some nerve & patience :wink:

**Comment by aliamini87** [comment]
دمت گرم!
موفق باشی.

**Comment by MatanRubin** [comment]
Hi, thank you for this plugin!
I encounter this issue using Obsidian 1.0.3 and Dynamic RTL plugin version 0.2.11:
![image](https://user-images.githubusercontent.com/4488227/208689418-bcbf345f-a581-458b-8d64-0d9fcab82a4b.png)

What am I missing?

**Comment by mwxgaf** [comment]
Hi
I checked out & could not reach a situation that faces this problem. Do you pressed enter (new line) for the first task? or does changing theme fix the problem?

**Comment by MatanRubin** [comment]
I tried this again to make sure I don't have anything else installed that might be causing this. I created a new test vault and installed Obsidian Tasks and Dynamic RTL, nothing else. I enabled tasks and set the global filter to `#task` and enabled the Remove Global Filter setting:
![image](https://user-images.githubusercontent.com/4488227/208841171-a412fb09-6c23-4a77-9ece-1888c3384347.png)

So far everything works as expected. 
Now I enabled the Dynamic RTL plugin and switch to viewing mode, and I get this:
![image](https://user-images.githubusercontent.com/4488227/208841316-59bf2e17-025c-47af-935c-08e63a30eb01.png)

The markdown I entered for this was exactly this:
```
- [ ] #task task 1
- [ ] #task task 2
```

Note that you need to restart Obsidian for changes to take effect once you change ANY setting in the Tasks plugin.

**Comment by mwxgaf** [comment]
![image](https://user-images.githubusercontent.com/39344217/208965287-cb200455-88d2-4e3c-9f2e-7065d7e86cbc.png)
 
I did exactly what you said but I could not face the problem again. I'm sorry
I use Things theme (This may help)

**Comment by MatanRubin** [comment]
I tried it again, this time with the default theme and again with the Things theme. I get the same result each and every time.
How can we debug this further? I'd love to give you any output from my environment that might help you identify the issue...

**Comment by MatanRubin** [comment]
Looking at the HTML in the developer tools shows the issue - in the first task there's an additional `div` that doesn't exist in the second task.

![image](https://user-images.githubusercontent.com/4488227/209318257-d60c5ef3-5403-4907-a913-bc47fe018bf3.png)

I'm not really sure how the plugin works, but this additional div seems to be the root cause. Do you know why it is added in the first task? Anything I can do to find out?

**Comment by ma-sadeghi** [comment]
Could you maybe create a brand new vault and try again?

**Comment by MatanRubin** [comment]
This was done in a brand new vault

**Comment by ma-sadeghi** [comment]
It's very strange, because I can't reproduce it either. I'm using the Minimal theme.

**Comment by mwxgaf** [comment]
@MatanRubin & @ma-sadeghi
Thank for your help & your detailed info. :rose: 
The problem is fixed in [new version](https://github.com/mwxgaf/obsidian-dynamic-rtl/releases/tag/0.2.12)
Please update the plugin from app & check if its fixed for you or not :heavy_check_mark:

**Comment by MatanRubin** [comment]
Awesome! Thank you so much! Will give it a try once the new version is available and report back!

**Comment by MatanRubin** [comment]
Updated to latest and the issue is resolved! Thank you so much for your help and for this great plugin!
